### ISSUE TITLE
Report from Qualcomm: problem installing CK 2.0.1

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#141]
From Anton on Slack: Qualcomm have reported a problem when running our CK-QAIC workflow with CK v2.0.1 installed via pip:
...
```
Traceback (most recent call last):
  File "/usr2/xxx/.local/bin/ck", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr2/xxx/.local/bin/ck", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr2/xxx/.local/bin/ck", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ck==2.0.1' distribution was not found and is required by the application
downgrading to CK v1.55.5 has resolved the issue
```

OS: CentOS 7

**Comment by gfursin** [comment]
Hmm, I created a docker container with CentOS 7 and Python 3.6.8 and installed ck 2.0.1 and 2.0.3 without any problem:

```
ck run docker:ck-template-x8664-centos-7
Executing command line:
  docker run -it octoml/ck-template-x8664-centos-7  bash

[ckuser@defe05583095 ~]$ python3 --version
Python 3.6.8
[ckuser@defe05583095 ~]$ ck
CK version: 2.0.1

Python executable used by CK: /usr/bin/python3

Python version used by CK: 3.6.8 (default, Nov 16 2020, 16:55:22)
   [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Path to the default repo: /home/ckuser/.local/lib/python3.6/site-packages/ck/repo
Path to the local repo:   /home/ckuser/CK/local
Path to CK repositories:  /home/ckuser/CK

Documentation:        https://github.com/ctuning/ck/wiki
CK Google group:      https://bit.ly/ck-google-group
CK Slack channel:     https://cKnowledge.org/join-slack
Stable CK components: https://cKnowledge.io
[ckuser@defe05583095 ~]$
```

However, we were suggested to rely on the official Python setuptool mechanism to generate ck binary rather than having our own ck scripts. All our internal tests pass on Ubuntu with Python 3.6+. But maybe this mechanism is not working in some corner cases.

@psyhtest - can you please ask your colleagues from Qualcomm to provide more details about their environment, i.e. if they use a virtual environment or some unusual python distro? Do they use Docker image or native installation? We will be happy to help them with the transition to the newer version while making sure that CK supports most of the platforms outthere ...

Thanks a lot again for reporting!

**Comment by gfursin** [comment]
I googled "ModuleNotFoundError: No module named 'importlib.metadata'" and there are not so many occurrences. Seems like a rare issue with the Python installation. Even though we prefer to use a newer and more standard way of installing CK, we also want to support as many users as possible...

**Comment by arjunsuresh** [comment]
This issue can be closed I guess. We haven't faced this issue yet using ck==2.5.8 on Qualcomm systems

**Comment by gfursin** [comment]
Cool! Thank you for confirming, @arjunsuresh !
