### ISSUE TITLE
FileNotFoundError for an existing directory

### ISSUE THREAD

**Issue by thrisha-rk** [mlcommons/ck#274]
The script I am running :
```
python3 -m pip install cmind
cm pull repo mlcommons@ck
cm run script --tags=app,mlperf,_resnet50,_onnxruntime  --output_dir=$HOME/final_results \
--env.CM_LOADGEN_MODE=performance \
--env.CM_LOADGEN_SCENARIO=Offline
```

This halts because of FileNotFoundError of directory. That directory is present in my local, however it is not being recognised.
```
Starting Compliance Runs...
  - run postprocess ...
Traceback (most recent call last):
  File "/home/user/.local/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/home/user/.local/lib/python3.8/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/home/mcw/.local/lib/python3.8/site-packages/cmind/core.py", line 485, in access
    r = action_addr(i)
  File "/home/user/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1059, in run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/home/user/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1799, in prepare_and_run_script_with_postprocessing
    r = customize_code.postprocess(ii)
  File "/home/user/CM/repos/mlcommons@ck/cm-mlops/script/app-mlperf-inference-vision-reference/customize.py", line 270, in postprocess
    os.chdir(run['OUTPUT_DIR'])

FileNotFoundError: [Errno 2] No such file or directory: "'/home/user/final_results/test_results/onnxruntime-cpu/resnet50/offline/performance/run_1'"

```
This path is available and exists in my local.

**Comment by arjunsuresh** [comment]
Can you please try the following commands? Over the last 2 days we had some refactoring in the app-mlperf-inference-script script.

```
cm run script --tags=app,mlperf,_resnet50,_onnxruntime  --output_dir=$HOME/final_results --env.CM_LOADGEN_MODE=performance --env.CM_LOADGEN_SCENARIO=Offline --add_deps.loadgen.version=r2.1 --add_deps_recursive.inference-src.version=octoml 
```

For accuracy (just change `performance` in above command to `accuracy`)
```
cm run script --tags=app,mlperf,_resnet50,_onnxruntime  --output_dir=$HOME/final_results --env.CM_LOADGEN_MODE=accuracy --env.CM_LOADGEN_SCENARIO=Offline --add_deps.loadgen.version=r2.1 --add_deps_recursive.inference-src.version=octoml 
```

**Comment by gfursin** [comment]
Sure @arjunsuresh . Thanks a lot for the fixes and the update. I will check the updated CK2 on Monday morning and we can sync then!

**Comment by thrisha-rk** [comment]
These commands works for me, I have the accuracy results for the 5 test images.

**Comment by arjunsuresh** [comment]
Thanks @thrisha-rk for confirming. Closing this issue.
