### ISSUE TITLE
Handling CLI strings with =

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#453]
Currently CLI strings containing `=` are not working in CM.
```
cm run script --tags=run,docker,container --script_tags=app,mlperf,inference,generic,_resnet50,_python,_onnxruntime,_cpu --run_cmd_extra="--adr.inference-src.tags=_octoml --adr.compiler.tags=gcc --quiet"
Traceback (most recent call last):
  File "/home/arjun/.local/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/home/arjun/.local/lib/python3.10/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/home/arjun/.local/lib/python3.10/site-packages/cmind/core.py", line 178, in access
    r = cmind.cli.parse(i)
  File "/home/arjun/.local/lib/python3.10/site-packages/cmind/cli.py", line 114, in parse
    key,value = a.split('=')
ValueError: too many values to unpack (expected 2)
```

**Comment by xintin** [comment]
I am trying to understand the flow here.

A quick question, in the command, 
`cm run script --tags=run,docker,container --script_tags=app,mlperf,inference,generic,_resnet50,_python,_onnxruntime,_cpu --run_cmd_extra="--adr.inference-src.tags=_octoml --adr.compiler.tags=gcc --quiet"`

how should we treat `--run_cmd_extra`? 
Without that, the rest of the cmd will look something like `['--tags=run,docker,co
ntainer', '--script_tags=app,mlperf,inference,generic,_resnet50,_python,_onnxruntime,_cpu', '--adr.in
ference-src.tags=_octoml', '--adr.compiler.tags=gcc', '--quiet']`

Should it be: other tags + `run_cmd_extra: {'adr': {'inference-
src': {'tags': '_octoml'}, 'compiler': {'tags': 'gcc'}}, 'quiet': True}`

Thank you.

**Comment by arjunsuresh** [comment]
Hi @xintin , actually here `--run_cmd_extra` is an input to the called CM script (`--tags=run,docker,container`). And it is of type string. So, it should be `--run_cmd_extra="--adr.inference-src.tags=_octoml --adr.compiler.tags=gcc --quiet"`.

**Comment by gfursin** [comment]
By the way, just a note that we plan to simplify this interface 
considerably - it's a low-level basic block that will be wrapper with a 
more user-friendly interface soon ;) !

**Comment by xintin** [comment]
@gfursin Yes, I kind of felt so after taking a look into cli.py. Looking forward to it. :)

@arjunsuresh, got it. Thanks
I was asking after it parses the argv - the intermediate object, {key. val} pair.

**Comment by gfursin** [comment]
Fixed: https://github.com/octoml/ck/commit/1a9dacd71dc980d8e596951556d85ea0e5b46568
