### ISSUE TITLE
CUDA sudo installation error

### ISSUE THREAD

**Issue by ghost** [mlcommons/ck#626]
Currently trying to run the `cm run script "get cuda" --out=json` script. Have cuda, tensorRT, and cudann installed. Not sure if I'm missing any prerequisites, also do not have sudo perms on node. Thanks.

```     Make your selection or press Enter for 0: 1

      Selected 1: /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-toolkit
  - Found script::get-cuda-toolkit,46d133d9ef92422d in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-toolkit
  - Checking if script execution is already cached ...
    - Searching for cached script outputs with the following tags: -tmp,get,cuda,toolkit,cuda-compiler,cuda-toolkit,nvcc,get-nvcc,get-cuda
  - Creating new "cache" script artifact in the CM local repository ...
    - Tags: tmp,get,cuda,toolkit,cuda-compiler,cuda-toolkit,nvcc,get-nvcc,get-cuda,script-artifact-46d133d9ef92422d
  - Changing to /project/mclesi2/CM/repos/local/cache/5246d8511fc54160
  - Running preprocess ...
    # Requested paths: /usr/local/cuda/bin:/usr/cuda/bin
  - Checking prehook dependencies on other CM scripts:

    * Searching for collective script(s) with tags "install,cuda,prebuilt"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,install,cuda,prebuilt
        - Number of cached script outputs found: 0
      - Found script::install-cuda-prebuilt,14eadcd42ba340c3 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/install-cuda-prebuilt
      - Checking if script execution is already cached ...
        - Searching for cached script outputs with the following tags: -tmp,install,cuda,prebuilt,prebuilt-cuda,install-prebuilt-cuda
      - Creating new "cache" script artifact in the CM local repository ...
        - Tags: tmp,install,cuda,prebuilt,prebuilt-cuda,install-prebuilt-cuda,script-artifact-14eadcd42ba340c3
      - Changing to /project/mclesi2/CM/repos/local/cache/08b8cff953624e64
      - Version is not specified - use either default_version from meta or min/max/usable: 11.8.0
      - Checking dependencies on other CM scripts:

        * Searching for collective script(s) with tags "detect,os"
          - Number of scripts found: 1
          - Found script::detect-os,863735b7db8c44fc in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/detect-os
          - Running preprocess ...

          - Running native script "/project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/run.sh" from temporal script "tmp-run.sh" in "/ddnA/project/lyan1/mclesi2/CM/repos/local/cache/08b8cff953624e64" ...

          - Running postprocess ...
          - running time of script "detect-os,detect,os,info": 0.29 sec.
      - Processing env after dependencies ...
        # potential PIP version string (if needed): ==11.8.0
      - Running preprocess ...

      - Running native script "/project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/install-cuda-prebuilt/run.sh" from temporal script "tmp-run.sh" in "/ddnA/project/lyan1/mclesi2/CM/repos/local/cache/08b8cff953624e64" ...

--2023-01-17 08:04:59--  https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.195.19.142
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.195.19.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4336730777 (4.0G) [application/octet-stream]
Saving to: ‘cuda_11.8.0_520.61.05_linux.run’

cuda_11.8.0_ 100%   4.04G   217MB/s    in 19s

2023-01-17 08:05:18 (216 MB/s) - ‘cuda_11.8.0_520.61.05_linux.run’ saved [4336730777/4336730777]


We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for mclesi2:
{
  "error": "Portable CM script failed (name = install-cuda-prebuilt, return code = 256)\n\nNote that it is often a portability problem of the third-party tool or native script that is wrapped and unified by this CM script.\nThe CM concept is to collaboratively fix such issues inside portable CM scripts to make existing tools and native script more portable, interoperable, deterministic and reproducible.\n\nPlease help the community by reporting the full log with the command line here:\n* https://github.com/mlcommons/ck/issues \n* https://bit.ly/mlperf-edu-wg\n\nThank you",
  "return": 2
}```

**Comment by arjunsuresh** [comment]
Hi @michaelclesi , just trying to understand why `cuda detect` failed. 
1. What is the path to cuda installation?
2. Is cuda installed with nvcc or is it just the libraries?

**Comment by arjunsuresh** [comment]
Thank you for your reply @michaelclesi. Can you please do the following?
```
cm run script "get cuda" --input=/usr/local/packages/cuda
```

**Comment by michaelclesi** [comment]
@arjunsuresh Heres my output

```[mclesi2@mike176 ~]$ cm run script "get cuda" --input=/usr/local/packages/cuda

* Searching for collective script(s) with tags "get,cuda"
  - Number of scripts found: 2
  - Searching for cached script outputs with the following tags: -tmp,get,cuda
    - Number of cached script outputs found: 0
    - More than 1 script found for "get,cuda":

      0) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib (get,cuda-rt,cuda,lib,cuda-lib,lib-only,runtime,get-cuda)
      1) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-toolkit (get,cuda,toolkit,cuda-compiler,cuda-toolkit,nvcc,get-nvcc,get-cuda)

      Make your selection or press Enter for 0: ^CTraceback (most recent call last):
  File "/ddnA/project/lyan1/mclesi2/.packages/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 535, in run
    select_script = select_script_artifact(list_of_found_scripts, 'script', recursion_spaces, False, script_tags_string, quiet, verbose)
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 3824, in select_script_artifact
    x = input(recursion_spaces+'      '+s+': ')
KeyboardInterrupt

[mclesi2@mike176 ~]$ module load cuda
[mclesi2@mike176 ~]$ cm run script "get cuda" --input=/usr/local/packages/cuda

* Searching for collective script(s) with tags "get,cuda"
  - Number of scripts found: 2
  - Searching for cached script outputs with the following tags: -tmp,get,cuda
    - Number of cached script outputs found: 0
    - More than 1 script found for "get,cuda":

      0) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib (get,cuda-rt,cuda,lib,cuda-lib,lib-only,runtime,get-cuda)
      1) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-toolkit (get,cuda,toolkit,cuda-compiler,cuda-toolkit,nvcc,get-nvcc,get-cuda)

      Make your selection or press Enter for 0: 0

      Selected 0: /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib
  - Found script::get-cuda-lib,49df6b19c3fb496e in /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib
  - Checking if script execution is already cached ...
    - Searching for cached script outputs with the following tags: -tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda
  - Creating new "cache" script artifact in the CM local repository ...
    - Tags: tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda,script-artifact-49df6b19c3fb496e
  - Changing to /ddnA/project/lyan1/mclesi2/CM/repos/local/cache/f9f4b66615ea4082
  - Running preprocess ...

CM error: CUDA installation not found in default paths. Please set --input to the installed path!
[mclesi2@mike176 ~]$ the
bash: the: command not found
[mclesi2@mike176 ~]$ cm run script "get cuda" --input=/usr/local/packages/cuda

* Searching for collective script(s) with tags "get,cuda"
  - Number of scripts found: 2
  - Searching for cached script outputs with the following tags: -tmp,get,cuda
    - Number of cached script outputs found: 0
    - More than 1 script found for "get,cuda":

      0) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib (get,cuda-rt,cuda,lib,cuda-lib,lib-only,runtime,get-cuda)
      1) /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-toolkit (get,cuda,toolkit,cuda-compiler,cuda-toolkit,nvcc,get-nvcc,get-cuda)

      Make your selection or press Enter for 0: 0

      Selected 0: /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib
  - Found script::get-cuda-lib,49df6b19c3fb496e in /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-cuda-lib
  - Checking if script execution is already cached ...
    - Searching for cached script outputs with the following tags: -tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda
  - Creating new "cache" script artifact in the CM local repository ...
    - Tags: tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda,script-artifact-49df6b19c3fb496e
  - Changing to /ddnA/project/lyan1/mclesi2/CM/repos/local/cache/f9f4b66615ea4082
  - Running preprocess ...

CM error: CUDA installation not found in default paths. Please set --input to the installed path!```

**Comment by michaelclesi** [comment]
The previous output was for option 0, option 1 gives me ```CM error: file /usr/local/packages/cuda doesn't exist!```

**Comment by arjunsuresh** [comment]
Sorry, my bad. `--input` should point to the nvcc file. Can you please try this?
```
cm run script "get cuda toolkit" --env.CM_TMP_PATH=/usr/local/packages/cuda
```

**Comment by michaelclesi** [comment]
cuda downloads fine, however I do not have sudo access. Gives a 256 errors when I ctrl+c the password prompt. I have cudatoolkit and a 'module' implemented by the HPC admins for cuda 11.6. Anyway to bypass the cuda driver needing sudo?

**Comment by arjunsuresh** [comment]
Actually if nvcc detection is successful, then even cuda download is not necessary - so it again failed. Does one of the below 2 commands help?
```
cm run script "get cuda lib" --env.CM_TMP_PATH=/usr/local/packages/cuda
```

```
cm run script "get cuda toolkit" --input=<FULL_PATH_TO_NVCC_BIN>
```

**Comment by michaelclesi** [comment]
the toolkit script worked, however now it gets mad about my cudnn, I'll update you when I unpack the rpm

**Comment by arjunsuresh** [comment]
Oh. The `CM script` for cudnn copies the cuddn libraries to the `CUDA_LIB_PATH`. So, it'll need sudo permission. Is cudnn libraries already installed? If so we can skip the cudnn install. Are you trying to run `app mlperf inference` on CUDA?

**Comment by michaelclesi** [comment]
Yes, I'm trying to run the inference on cuda, no dice on cudnn libraries being installed.

**Comment by michaelclesi** [comment]
I moved to another cluster that does indeed have the cudnn libraries. Got no problems beyond a weird json file error. Any ideas?

```[mclesi2@mike176 lib64]$ cm run script "app mlperf inference generic _python _retinanet _onnxruntime _cuda" \
>      --adr.python.name=mlperf-cuda \
>      --scenario=Offline \
>      --mode=performance \
>      --clean

* Searching for collective script(s) with tags "app,mlperf,inference,generic" and variations "python,retinanet,onnxruntime,cuda"
  - Number of scripts found: 1
  - Found script::app-mlperf-inference,d775cac873ee4231 in /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/app-mlperf-inference
    Prepared variations: _python,_retinanet,_onnxruntime,_cuda,_reference,_test
  - Checking dependencies on other CM scripts:

    * Searching for collective script(s) with tags "detect,os"
      - Number of scripts found: 1
      - Found script::detect-os,863735b7db8c44fc in /ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/detect-os
      - Running preprocess ...
Traceback (most recent call last):
  File "/ddnA/project/lyan1/mclesi2/.packages/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1228, in run
    r = self._call_run_deps(deps, self.local_env_keys, local_env_keys_from_meta, env, state, const, const_state, add_deps_recursive,
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2071, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2168, in _run_deps
    r = self.cmind.access(ii)
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1411, in run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/ddnA/project/lyan1/mclesi2/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 3318, in prepare_and_run_script_with_postprocessing
    r = utils.save_json(file_name = tmp_file_state, meta = state)
  File "/ddnA/project/lyan1/mclesi2/.packages/lib/python3.9/site-packages/cmind/utils.py", line 203, in save_json
    with open(file_name, 'w', encoding = encoding, newline='\n') as jf:
PermissionError: [Errno 13] Permission denied: 'tmp-state.json'```

**Comment by arjunsuresh** [comment]
oh okay. I'm not sure how that can be done without sudo as cuda is installed in sys path. @gfursin any suggestions?

With sudo access we can do as follows:

```
cm run script --tags=get,cudnn --input=<CUDNN_TAR_FILE>
```
Tar file can be downloaded from [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar)

Similarly, tensorrt must also be installed. This does not need sudo access.

```
cm run script --tags=get,tensorrt --input=<TENSORRT_TAR_FILE>
```
Tar file can be downloaded from [here](https://developer.nvidia.com/nvidia-tensorrt-8x-download)

**Comment by arjunsuresh** [comment]
@michaelclesi That's a permission error. Are you running the command from some system path?

**Comment by michaelclesi** [comment]
@arjunsuresh So on the new cluster, we do have cudnn. The 'get cuda' return the expected output; running the benchmarks give the same --input error, even providing the relevant input tag.

**Comment by michaelclesi** [comment]
Heres the output for the 'get cuda command

```  "env": {
    "+CPLUS_INCLUDE_PATH": [
      "/usr/local/packages/cuda/11.0.2/torz3pye/include"
    ],
    "+C_INCLUDE_PATH": [
      "/usr/local/packages/cuda/11.0.2/torz3pye/include"
    ],
    "+DYLD_FALLBACK_LIBRARY_PATH": [],
    "+LD_LIBRARY_PATH": [],
    "CM_CUDA_CACHE_TAGS": "version-11.0",
    "CM_CUDA_INSTALLED_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye",
    "CM_CUDA_PATH_BIN": "/usr/local/packages/cuda/11.0.2/torz3pye/bin",
    "CM_CUDA_PATH_INCLUDE": "/usr/local/packages/cuda/11.0.2/torz3pye/include",
    "CM_CUDA_PATH_LIB": "/usr/local/packages/cuda/11.0.2/torz3pye/lib64",
    "CM_CUDA_PATH_LIB_CUDNN_EXISTS": "no",
    "CM_CUDA_VERSION": "11.0",
    "CM_NVCC_BIN": "nvcc",
    "CM_NVCC_BIN_WITH_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye/bin/nvcc",
    "CUDA_HOME": "/usr/local/packages/cuda/11.0.2/torz3pye",
    "CUDA_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye"
  },
  "new_env": {
    "+CPLUS_INCLUDE_PATH": [
      "/usr/local/packages/cuda/11.0.2/torz3pye/include"
    ],
    "+C_INCLUDE_PATH": [
      "/usr/local/packages/cuda/11.0.2/torz3pye/include"
    ],
    "+DYLD_FALLBACK_LIBRARY_PATH": [],
    "+LD_LIBRARY_PATH": [],
    "CM_CUDA_CACHE_TAGS": "version-11.0",
    "CM_CUDA_INSTALLED_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye",
    "CM_CUDA_PATH_BIN": "/usr/local/packages/cuda/11.0.2/torz3pye/bin",
    "CM_CUDA_PATH_INCLUDE": "/usr/local/packages/cuda/11.0.2/torz3pye/include",
    "CM_CUDA_PATH_LIB": "/usr/local/packages/cuda/11.0.2/torz3pye/lib64",
    "CM_CUDA_PATH_LIB_CUDNN_EXISTS": "no",
    "CM_CUDA_VERSION": "11.0",
    "CM_NVCC_BIN": "nvcc",
    "CM_NVCC_BIN_WITH_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye/bin/nvcc",
    "CUDA_HOME": "/usr/local/packages/cuda/11.0.2/torz3pye",
    "CUDA_PATH": "/usr/local/packages/cuda/11.0.2/torz3pye"
  },
  "new_state": {},
  "return": 0,
  "state": {}
}```

**Comment by arjunsuresh** [comment]
You mean the following error?
```
Please use --input option to point to the cudnn tar file
```

**Comment by michaelclesi** [comment]
```            - Prepared variations: _cudnn
            - Searching for cached script outputs with the following tags: -tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda,_cudnn
          - Creating new "cache" script artifact in the CM local repository ...
            - Tags: tmp,get,cuda,cuda-rt,lib,cuda-lib,lib-only,runtime,get-cuda,_cudnn,script-artifact-49df6b19c3fb496e
          - Changing to /ddnA/project/lyan1/mclesi2/CM/repos/local/cache/e6c0535e0cad4a1a
          - Running preprocess ...
            # Requested paths: /usr/local/cuda/lib:/usr/cuda/lib:/usr/local/cuda/lib64:/usr/cuda/lib64

CM error: CUDA installation not found in default paths. Please set --input to the installed path!```

**Comment by michaelclesi** [comment]
We ran this command:

```cm run script "app mlperf inference generic _python _retinanet _onnxruntime _cuda" \
     --adr.python.name=mlperf-cuda \
     --scenario=Offline \
     --mode=performance \
     --clean```

**Comment by arjunsuresh** [comment]
It looks like `get,cuda,toolkit` was detected but while running the `app`, `get,cuda,lib` was selected. Can you please try selecting the `get,cuda,toolkit` when prompted?

**Comment by gfursin** [comment]
Hi @michaelclesi .
Thank you very much for your feedback - we are updating our CUDA detection scripts to encode your suggestions in a user-friendly and will get back to you shortly! If you feel that they are still not that user-friendly, please tell us!
We can also jump on a conf-call to make sure that everything works fine!
We will also update our tutorial to detect/install CUDA with cuDNN for MLPerf - we are nearly ready to run native NVIDIA MLPerf benchmark via unified CM interface and will be glad to test it together too to compare results ...

**Comment by gfursin** [comment]
We improved the functionality of this package. If further assistance is required, please use cm4mlops repo: https://github.com/mlcommons/cm4mlops .
