### ISSUE TITLE
deepsparse implementation issue

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#640]
@arjunsuresh . I used this [CK2/CM GUI](https://cknowledge.org/cm-gui/?tags=run,mlperf,inference,generate-run-cmds) to generate CM CMD to run deepsparse implementation but it has failed. 

Here is the auto-generated CMD:

```bash
cm run script --tags=run,mlperf,inference,generate-run-cmds,_dashboard,_submission,_short  \
   --adr.python.name=mlperf \
   --adr.python.version_min=3.8 \
   --adr.compiler.tags=gcc \
   --submitter=GuiTestFromTheCommunity \
   --implementation=reference \
   --model=bert-99 \
   --precision=fp32 \
   --backend=deepsparse \
   --hw_name=default \
   --device=cpu \
   --scenario=Offline \
   --execution_mode=test \
   --max_batchsize=1 \
   --dashboard_wb_user=cmind \
   --dashboard_wb_project=cm-mlperf-dse-testing \
   --clean 
```

The error is the following:
```bash
Archive:  squad1.1.zip
  inflating: dev-v1.1.json
  inflating: train-v1.1.json
          - Running postprocess ...
          - Removing tmp tag in the script cached output c91e86348fed4c15 ...
          - cache UID: c91e86348fed4c15
          - running time of script "get,dataset,squad,language-processing,validation,training,original": 2.20 sec.

        * Searching for collective script(s) with tags "get,ml-model,language-processing,bert,raw" and variations "deepsparse,fp32"
          - Number of scripts found: 1
          - Searching for cached script outputs with the following tags: -tmp,get,ml-model,language-processing,bert,raw,_deepsparse,_fp32
            - Number of cached script outputs found: 0
          - Found script::get-ml-model-bert-large-squad,5e865dbdc65949d2 in /home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/script/get-ml-model-bert-large-squad
            Prepared variations: _deepsparse,_fp32
          - Checking if script execution is already cached ...
            - Prepared variations: _deepsparse,_fp32
            - Searching for cached script outputs with the following tags: -tmp,get,ml-model,language-processing,bert,raw,bert-large,bert-squad,language,_deepsparse,_fp32
          - Creating new "cache" script artifact in the CM local repository ...
            - Tags: tmp,get,ml-model,language-processing,bert,raw,bert-large,bert-squad,language,_deepsparse,_fp32,script-artifact-5e865dbdc65949d2
          - Changing to /home/rsa-key-fgg-universal/CM/repos/local/cache/7472a2b25cc14ac1
          - Running preprocess ...
Traceback (most recent call last):
  File "/opt/conda/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.7/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/opt/conda/lib/python3.7/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 1355, in run
    r = customize_code.preprocess(ii)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/script/run-mlperf-inference-app/customize.py", line 125, in preprocess
    add_deps_recursive, 'silent': silent, 'print_env': print_env, 'print_deps': print_deps})
  File "/opt/conda/lib/python3.7/site-packages/cmind/core.py", line 607, in access
    return cm.access(i)
  File "/opt/conda/lib/python3.7/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 1420, in run
    remembered_selections, variation_tags_string, found_cached, debug_script_tags, verbose, show_time, extra_recursion_spaces, run_state)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 2106, in _call_run_deps
    verbose, show_time, extra_recursion_spaces, run_state)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 2201, in _run_deps
    r = self.cmind.access(ii)
  File "/opt/conda/lib/python3.7/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 1251, in run
    remembered_selections, variation_tags_string, False, debug_script_tags, verbose, show_time, extra_recursion_spaces, run_state)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 2106, in _call_run_deps
    verbose, show_time, extra_recursion_spaces, run_state)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 2201, in _run_deps
    r = self.cmind.access(ii)
  File "/opt/conda/lib/python3.7/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/automation/script/module.py", line 1355, in run
    r = customize_code.preprocess(ii)
  File "/home/rsa-key-fgg-universal/CM/repos/octoml@ck/cm-mlops/script/get-ml-model-bert-large-squad/customize.py", line 16, in preprocess
    url = env['CM_PACKAGE_URL']
KeyError: 'CM_PACKAGE_URL'
```

Do you mind to check it, please ...
Thanks a lot!

**Comment by gfursin** [comment]
Oh, yes, only int8 is supported. Now I have an error with max batchsize. Let's check it too ... Thanks!

**Comment by gfursin** [comment]
It works in the latest PR. Thanks!
