### ISSUE TITLE
Error on m1 processor while running run_mobilenet.py script.

### ISSUE THREAD

**Issue by Sachin-23** [mlcommons/ck#661]
System Details: 
Processor: m1 macbook 2020 model
OS: macos big sur 11.7.3

I think it has to something to do with m1 processor. Env variable CM_HOST_PLATFORM_FLAVOR is set to `arm64`. 

```
Traceback (most recent call last):
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/script/run-mlperf-inference-app/run_mobilenet.py", line 98, in <module>
    r = cmind.access(cm_input)
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 607, in access
    return cm.access(i)
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1289, in run
    r = customize_code.preprocess(ii)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/script/run-mlperf-inference-app/customize.py", line 138, in preprocess
    r = cm.access({'action':'run', 'automation':'script', 'tags': tags, 'quiet': 'true',
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 607, in access
    return cm.access(i)
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1366, in run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 3543, in prepare_and_run_script_with_postprocessing
    r = script_automation._call_run_deps(posthook_deps, local_env_keys, local_env_keys_from_meta, env, state, const, const_state,
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2204, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2306, in _run_deps
    r = self.cmind.access(ii)
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1183, in run
    r = self._call_run_deps(deps, self.local_env_keys, local_env_keys_from_meta, env, state, const, const_state, add_deps_recursive, 
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2204, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 2306, in _run_deps
    r = self.cmind.access(ii)
  File "/opt/homebrew/lib/python3.10/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 1289, in run
    r = customize_code.preprocess(ii)
  File "/Users/s4ch1n/CM/repos/mlcommons@ck/cm-mlops/script/get-lib-armnn/customize.py", line 16, in preprocess
    env['CM_LIB_ARMNN_PREBUILT_BINARY_URL'] = url
UnboundLocalError: local variable 'url' referenced before assignment
```

**Comment by arjunsuresh** [comment]
Thanks a lot @Sachin-23 for reporting this issue - it is very useful to the community. As you have correctly diagnosed issue is indeed with macos as there are no official prebuilt binary for macos. 
https://github.com/ARM-software/armnn#pre-built-binaries

Since M1 is aarch64, building from source is an option but we haven't yet tried it yet nor added to CM scripts.

But armnn library is not on by default in [this script](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/run-mlperf-inference-app/run_mobilenet.py) - how did you turn it on? Are you using the octoml fork?

**Comment by Sachin-23** [comment]
Sorry for the late response @arjunsuresh, I didn't change anything in the script by default it was turned on and it started checking CPU architecture for armnn library. I am using this repository which I pulled from `cm pull repo mlcommons@ck` command.

**Comment by arjunsuresh** [comment]
Thank you @Sachin-23 for confirming. We have now made this run script in to a CM script which can get rid of such issues which can happen due to manual edits. 
https://github.com/mlcommons/ck/tree/master/cm-mlops/script/run-mlperf-inference-mobilenet-models

### Run Commands
```
cm run script --tags=run,mobilenet-models,_find-performance
```
```
cm run script --tags=run,mobilenet-models,_submission
```
```
cm run script --tags=run,mobilenet-models,_armnn,_find-performance
```
cm run script --tags=run,mobilenet-models,_armnn,_submission
```
cm run script --tags=run,mobilenet-models,_armnn,_neon,_find-performance
```
cm run script --tags=run,mobilenet-models,_armnn,_neon,_submission
```
```
cm run script --tags=run,mobilenet-models,_armnn,_opencl,_find-performance
```
cm run script --tags=run,mobilenet-models,_armnn,_opencl,_submission
```

**Comment by gfursin** [comment]
Hi @arjunsuresh - is this ticket resolved?

**Comment by arjunsuresh** [comment]
Yes, this is resolved now. Closing
