### ISSUE TITLE
MLPerf power server is failing on Ubuntu 23.04

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#807]
MLPerf power server is failing on Ubuntu 23.04.
```
cm run script --tags=mlperf,power,server --device_type=0 --device_portp=/dev/usbtmc1
```

```
ptd-server 2023-06-23 15:19:01,466 [INFO] Running PTDaemon: ['/media/arjun/T7_Touch/hp-envy/CM/repos/local/cache/9b3695ca8255492a/power/inference_v1.0/ptd-linux-x86', '-l', '/tmp/tmps4bce7up/ptd_logfile.txt', '-p', '8888', '0', '/dev/usbtmc1']
ptd-server 2023-06-23 15:19:01,668 [ERROR] Could not start PTDaemon
Traceback (most recent call last):
  File "/media/arjun/T7_Touch/hp-envy/CM/repos/local/cache/0080d41a7adc4d61/power-dev/ptd_client_server/../ptd_client_server/lib/server.py", line 394, in start
    self._start()
  File "/media/arjun/T7_Touch/hp-envy/CM/repos/local/cache/0080d41a7adc4d61/power-dev/ptd_client_server/../ptd_client_server/lib/server.py", line 440, in _start
    raise RuntimeError("PTDaemon unexpectedly terminated")
RuntimeError: PTDaemon unexpectedly terminated
ptd-server 2023-06-23 15:19:01,670 [INFO] Force stopping ptd...
```

**Comment by arjunsuresh** [comment]
This being an issue with SPEC PTDaemon is likely to be resolved only when we have a [new PTDaemon](https://www.spec.org/power/docs/SPECpower-PTD-Update_Process.html) release from SPEC.

**Comment by arjunsuresh** [comment]
For now, the best option is to [use CM docker](https://github.com/mlcommons/ck/blob/master/docs/tutorials/mlperf-inference-power-measurement.md#running-the-power-server-inside-a-docker-container) on Ubuntu 23.04 as it is working pretty well.
