### ISSUE TITLE
"cm docker script --tags=detect,os -j" doesn't work on Windows

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#854]
Fails with 
```
Dockerfile generated at D:\Work1\CM\ck\cm-mlops\script\detect-os\dockerfiles\ubuntu_22.04.Dockerfile
* cm run script "run docker container"
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\!Progs\Python39\Scripts\cm-script.py", line 33, in <module>
    sys.exit(load_entry_point('cmind==1.5.0', 'console_scripts', 'cm')())
  File "C:\!Progs\Python39\lib\site-packages\cmind\cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "C:\!Progs\Python39\lib\site-packages\cmind\core.py", line 546, in access
    r = action_addr(i)
  File "D:\Work1\CM\ck\cm-mlops\automation\script\module.py", line 3299, in docker
    return utils.call_internal_module(self, __file__, 'module_misc', 'docker', i)
  File "C:\!Progs\Python39\lib\site-packages\cmind\utils.py", line 1562, in call_internal_module
    return getattr(tmp_module, module_func)(i)
  File "D:\Work1\CM\ck\cm-mlops\automation\script\module_misc.py", line 1400, in docker
    r = self_module.cmind.access(cm_docker_input)
  File "C:\!Progs\Python39\lib\site-packages\cmind\core.py", line 546, in access
    r = action_addr(i)
  File "D:\Work1\CM\ck\cm-mlops\automation\script\module.py", line 1377, in run
    r = customize_code.preprocess(ii)
  File "D:\Work1\CM\ck\cm-mlops\script\run-docker-container\customize.py", line 30, in preprocess
    docker_image = subprocess.check_output(CMD, shell=True).decode("utf-8")
  File "C:\!Progs\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\!Progs\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker images -q cm:detect-os 2> /dev/null' returned non-zero exit status 1.
```

Let's check it at some point ...

**Comment by gfursin** [comment]
Fixed in https://github.com/mlcommons/ck/commit/1eaeb4c17ae3f20d3bbe09f9432c36fa6f7c33ec .
