### ISSUE TITLE
Failure when using python3.6

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#888]
Currently, there is a problem running CM using python 3.6. For example
```
cmr "run mobilenet-models _tflite _accuracy-only" --adr.compiler.tags=gcc --results_dir=$HOME/mobilenet_results
```

produces the below error 
```
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/cmr", line 11, in <module>
    load_entry_point('cmind==1.5.1', 'console_scripts', 'cmr')()
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/cli.py", line 76, in run_script
    return run(['run', 'script'] + argv)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 546, in access
    r = action_addr(i)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 1378, in run
    r = customize_code.preprocess(ii)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/script/run-mlperf-inference-mobilenet-models/customize.py", line 168, in preprocess
    r = cmind.access(cm_input)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 667, in access
    return cm.access(i)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 546, in access
    r = action_addr(i)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 1378, in run
    r = customize_code.preprocess(ii)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/script/run-mlperf-inference-app/customize.py", line 148, in preprocess
    r = cm.access(ii)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 667, in access
    return cm.access(i)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 546, in access
    r = action_addr(i)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 1455, in run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 3787, in prepare_and_run_script_with_postprocessing
    add_deps_recursive, recursion_spaces, remembered_selections, variation_tags_string, found_cached, debug_script_tags, verbose)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 2317, in _call_run_deps
    verbose, show_time, extra_recursion_spaces, run_state)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 2462, in _run_deps
    r = self.cmind.access(ii)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/cmind/core.py", line 546, in access
    r = action_addr(i)
  File "/home/ec2-user/CM/repos/ctuning@mlcommons-ck/cm-mlops/automation/script/module.py", line 1372, in run
    ii = copy.deepcopy(customize_common_input)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
```

**Comment by gfursin** [comment]
Weird. Never saw it before. Is it only with MobileNets scripts? Is it possible to add Python 3.6 to some of our GitHub tests and check it with some reference MLPerf models?

**Comment by arjunsuresh** [comment]
@gfursin it is with the script module and is affecting all CM scripts. But some pass on retries.

**Comment by gfursin** [comment]
That's weird ... What do you think we should do?

**Comment by arjunsuresh** [comment]
For now we should suggest to use python 3.7+. After Friday we can get to the bottom of this problem. It is coming from `copy.deepcopy`.

**Comment by gfursin** [comment]
Sounds good! Thanks!

**Comment by gfursin** [comment]
@arjunsuresh . We mention that CM and most automations need Python 3.7+ . Should we close this ticket?

**Comment by arjunsuresh** [comment]
Sure Grigori.
